package router

// Router package — registers all Gin route groups.
//
// Route groups planned (wired per level):
//   - Public (no auth):        /api/v1/products, /api/v1/reviews
//   - Auth:                    /api/v1/auth/register, /api/v1/auth/login
//   - Seller (role-gated):     /api/v1/seller/...
//   - Buyer  (role-gated):     /api/v1/buyer/...
//   - Driver (role-gated):     /api/v1/driver/...
//   - Admin  (role-gated):     /api/v1/admin/...
